openapi: 3.0.3
info:
  title: Logistics Calculator API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /calculate:
    post:
      summary: Calculate logistics rates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalculationRequest"
      responses:
        "200":
          description: Calculation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalculationResponse"
        "400":
          description: Validation error
  /rates:
    get:
      description: New endpoint
      responses:
        200:
          description: New response
          content:
            application/json:
              schema:
                : 
    get:
      summary: Get base rates and coefficients
      responses:
        "200":
          description: Rate table
          content:
            application/json:
              schema:
                type: object
                properties:
                  currency:
                    type: string
                  factors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: number
  /history:
    get:
      summary: Get user calculation history
      security:
        - bearerAuth: []
      responses:
        "200":
          description: History list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CalculationResponse"
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CalculationRequest:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              id: { type: string }
              quantity: { type: integer }
              unit: { type: string }
              length_cm: { type: number }
              width_cm: { type: number }
              height_cm: { type: number }
        from:
          type: object
          properties:
            country: { type: string }
            postal_code: { type: string }
        to:
          type: object
          properties:
            country: { type: string }
            postal_code: { type: string }
        service:
          type: string
          enum: [standard, express]
        options:
          type: object
          properties:
            insurance: { type: boolean }
    CalculationResponse:
      type: object
      properties:
        requestId: { type: string }
        summary:
          type: object
          properties:
            total_items: { type: integer }
            total_weight_kg: { type: number }
            volumetric_weight_kg: { type: number }
            chargeable_weight_kg: { type: number }
            currency: { type: string }
        offers:
          type: array
          items:
            type: object
            properties:
              provider: { type: string }
              service: { type: string }
              price: { type: number }
              estimated_days: { type: integer }
